package com.github.concurrent.model.vo;

import lombok.Data;

import java.util.Date;

/**
 * <p>用户</p>
 *
 * @author <a href="mailto:7066450@qq.com">panxi</a>
 * @version 1.0.0
 * @since 1.0
 */
@Data
public class UserVo implements Cloneable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.id
     *
     * @mbg.generated Fri Nov 08 18:06:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.user_name
     *
     * @mbg.generated Fri Nov 08 18:06:50 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.user_password
     *
     * @mbg.generated Fri Nov 08 18:06:50 CST 2019
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.user_age
     *
     * @mbg.generated Fri Nov 08 18:06:50 CST 2019
     */
    private Byte userAge;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.create_time
     *
     * @mbg.generated Fri Nov 08 18:06:50 CST 2019
     */
    private Date createTime;

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}
