server:
  port: 6379
spring:
  redis:
    database: 0
    host: 47.105.137.27
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    #超时时间
    timeout: 2000
  devtools:
    add-properties: true

