package com.github.concurrent.model.generator;

import java.io.Serializable;
import java.util.Date;

public class Index implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_index.id
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_index.index_a
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private String indexA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_index.index_b
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private String indexB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_index.index_c
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private Byte indexC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_index.create_time
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_index.id
     *
     * @return the value of md_index.id
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_index.id
     *
     * @param id the value for md_index.id
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_index.index_a
     *
     * @return the value of md_index.index_a
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public String getIndexA() {
        return indexA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_index.index_a
     *
     * @param indexA the value for md_index.index_a
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setIndexA(String indexA) {
        this.indexA = indexA == null ? null : indexA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_index.index_b
     *
     * @return the value of md_index.index_b
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public String getIndexB() {
        return indexB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_index.index_b
     *
     * @param indexB the value for md_index.index_b
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setIndexB(String indexB) {
        this.indexB = indexB == null ? null : indexB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_index.index_c
     *
     * @return the value of md_index.index_c
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public Byte getIndexC() {
        return indexC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_index.index_c
     *
     * @param indexC the value for md_index.index_c
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setIndexC(Byte indexC) {
        this.indexC = indexC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_index.create_time
     *
     * @return the value of md_index.create_time
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_index.create_time
     *
     * @param createTime the value for md_index.create_time
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}