package com.github.concurrent.model.generator;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.id
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.user_name
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.user_password
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.user_age
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private Byte userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.version
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.create_time
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_user.delete_flag
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_user
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user.id
     *
     * @return the value of md_user.id
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user.id
     *
     * @param id the value for md_user.id
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user.user_name
     *
     * @return the value of md_user.user_name
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user.user_name
     *
     * @param userName the value for md_user.user_name
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user.user_password
     *
     * @return the value of md_user.user_password
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user.user_password
     *
     * @param userPassword the value for md_user.user_password
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user.user_age
     *
     * @return the value of md_user.user_age
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public Byte getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user.user_age
     *
     * @param userAge the value for md_user.user_age
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setUserAge(Byte userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user.version
     *
     * @return the value of md_user.version
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user.version
     *
     * @param version the value for md_user.version
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user.create_time
     *
     * @return the value of md_user.create_time
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user.create_time
     *
     * @param createTime the value for md_user.create_time
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_user.delete_flag
     *
     * @return the value of md_user.delete_flag
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_user.delete_flag
     *
     * @param deleteFlag the value for md_user.delete_flag
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}