package com.github.concurrent.dao.generator;

import com.github.concurrent.model.generator.Index;
import com.github.concurrent.model.generator.IndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    long countByExample(IndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    int deleteByExample(IndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    int insert(Index record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    int insertSelective(Index record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    List<Index> selectByExample(IndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    Index selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Index record, @Param("example") IndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    int updateByExample(@Param("record") Index record, @Param("example") IndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    int updateByPrimaryKeySelective(Index record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_index
     *
     * @mbg.generated Fri Nov 08 19:11:57 CST 2019
     */
    int updateByPrimaryKey(Index record);
}