package com.github.concurrent.dao.user;

import com.github.concurrent.model.user.DubboUser;
import com.github.concurrent.model.user.DubboUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DubboUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    long countByExample(DubboUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    int deleteByExample(DubboUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    int insert(DubboUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    int insertSelective(DubboUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    List<DubboUser> selectByExample(DubboUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    DubboUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") DubboUser record, @Param("example") DubboUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    int updateByExample(@Param("record") DubboUser record, @Param("example") DubboUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(DubboUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_user
     *
     * @mbg.generated Thu Oct 31 15:00:43 CST 2019
     */
    int updateByPrimaryKey(DubboUser record);
}